services:
  - type: web
    name: cap-solver-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn captcha_solver:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CAPSOLVER_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.0 